--
-- RagnarokOnline Settings File
-- Generated by RagnarokOnline OpenSetup, Version 2.12.0.406 ( http://ai4rei.net/p/opensetup )
--

-- Workaround for people with broken client folder
-- Note: The client removes this when it saves settings.
--
if OptionInfoList==nil then
	OptionInfoList = {}
end
if CmdOnOffList==nil then
	CmdOnOffList = {}
end
-- End of Workaround


-- Settings
--

OptionInfoList["Trilinear"] = 0
OptionInfoList["Bgm_Volume"] = 32
OptionInfoList["Effect_Volume"] = 33
OptionInfoList["MouseExclusive"] = 0
OptionInfoList["ISFULLSCREENMODE"] = 1
OptionInfoList["WIDTH"] = 1920
OptionInfoList["HEIGHT"] = 1080
OptionInfoList["BITPERPIXEL"] = 32
OptionInfoList["DEVICECNT"] = 3
OptionInfoList["MODECNT"] = 14
OptionInfoList["SPRITEMODE"] = 2
OptionInfoList["TEXTUREMODE"] = 2
CmdOnOffList["/bgm"] = 1
CmdOnOffList["/sound"] = 1
CmdOnOffList["/notrade"] = 0
CmdOnOffList["/noshift"] = 0
CmdOnOffList["/noctrl"] = 1
CmdOnOffList["/skillfail"] = 1
CmdOnOffList["/notalkmsg"] = 0
CmdOnOffList["/notalkmsg2"] = 0
CmdOnOffList["/showname"] = 0
CmdOnOffList["/fog"] = 0
CmdOnOffList["/aura"] = 1
CmdOnOffList["/window"] = 0
CmdOnOffList["/miss"] = 1
CmdOnOffList["/effect"] = 1
CmdOnOffList["/shopping"] = 1
CmdOnOffList["/stateinfo"] = 1
CmdOnOffList["/loginout"] = 1
CmdOnOffList["/snap"] = 0
CmdOnOffList["/itemsnap"] = 0
CmdOnOffList["/skillsnap"] = 1
CmdOnOffList["/camera"] = 1
CmdOnOffList["/hoai"] = 0
CmdOnOffList["/merai"] = 0
CmdOnOffList["/lightmap"] = 1
CmdOnOffList["/monsterhp"] = 1
CmdOnOffList["/q1"] = 0
CmdOnOffList["/q2"] = 0
CmdOnOffList["/aura2"] = 0
CmdOnOffList["/btg"] = 1
CmdOnOffList["/cashshop"] = 1
CmdOnOffList["/goldpc"] = 1
CmdOnOffList["/roulette"] = 1
CmdOnOffList["/quake"] = 1

-- Preserved client settings
--

OptionInfoList["OLD_WIDTH"] = 1920
OptionInfoList["ChangeChatMode"] = 1
OptionInfoList["bBlockPrivateTab"] = 0
OptionInfoList["bSoundEffectInItemSellWnd"] = 0
OptionInfoList["bItemDefaultSort"] = 1
OptionInfoList["ChannelCopID"] = 0
OptionInfoList["Window_XPos"] = 0
OptionInfoList["LockMouse"] = 0
OptionInfoList["Outdoor_ViewLatitude"] = -36
OptionInfoList["Indoor_ViewDistance"] = 300
OptionInfoList["bWarningPriceCheck"] = 0
OptionInfoList["/zoom"] = 0
OptionInfoList["ShowBattleFieldIcon"] = 1
OptionInfoList["AutoOpen1to1Window"] = 0
OptionInfoList["bLockItemDropFromItemWnd"] = 0
OptionInfoList["bGuildMemberListSort"] = 1
OptionInfoList["AutoOpen1to1Window_Friend"] = 0
OptionInfoList["Quadro de emblema"] = 0
OptionInfoList["Simplicity_SkillList"] = 1
OptionInfoList["bItemAscendingOrder"] = 0
OptionInfoList["PlaySound_Open1to1Window"] = 0
OptionInfoList["Window_YPos"] = 0
OptionInfoList["SkinName"] = "<Basic Skin>"
OptionInfoList["Outdoor_ViewDistance"] = 254.200058
OptionInfoList["Show_SkillDescript"] = 1
OptionInfoList["Indoor_ViewLatitude"] = -45
OptionInfoList["bShowMenuIcon"] = 0
OptionInfoList["OLD_HEIGHT"] = 1080
OptionInfoList["bItemDescendingOrder"] = 0
CmdOnOffList["/mable"] = 1
CmdOnOffList["/zoom"] = 0
CmdOnOffList["/mineffect"] = 1
